version: '3.9'

services:
  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address :9090
    expose:
      - "9000"
      - "9090"
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - ${DATA_PATH}/.data/minio/data:/data
      - ${DATA_PATH}/.data/minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=${OSS_USER}
      - MINIO_ROOT_PASSWORD=${OSS_PASSWORD}
    networks:
      - todolist

  mongodb:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}/.data/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    networks:
      - todolist

  todolist:
    build:
      context: ./
      dockerfile: Dockerfile
      cache_from:
        - node:18.14.2-alpine3.17
    volumes: # 开始使用，正常情况不应该存在
      - ./packages:/app/packages
    environment:
      - OSS_HOST=minio
      - DB_URL=mongodb://mongodb:27017
    ports:
      - "3000:3000"
      - "${SERVER_PROT}:${SERVER_PROT}"
    depends_on:
      - mongodb
      - minio
    networks:
      - todolist

networks:
  todolist:
    driver: bridge